<a href="https://colab.research.google.com/github/isabellamwright/project_voting/blob/main/CountyVA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

Loading the most recent estimates

In [ ]:

#df2 = pd.read_csv('0002_ds249_20205_county_E.csv',low_memory=False)
df4 = pd.read_csv('voting_VA.csv',low_memory=False)

In [ ]:
df = pd.read_csv('0002_ds250_20205_county_E.csv',low_memory=False)

In [ ]:
df = df.rename(columns=df.iloc[0])

In [ ]:
df

,1,GIS Join Match Code,Data File Year,State Postal Abbreviation,Region Code,Division Code,State Name,State Code,County Name,County Code,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
0,1,GIS Join Match Code,Data File Year,State Postal Abbreviation,Region Code,Division Code,State Name,State Code,County Name,County Code,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
1,2,G0100010,2016-2020,AL,NaN,NaN,Alabama,01,Autauga County,001,...,11323,2064,9259,2741,898,1843,1962,1255,707,0.4552
2,3,G0100030,2016-2020,AL,NaN,NaN,Alabama,01,Baldwin County,003,...,44915,5851,39064,14209,2921,11288,9539,4370,5169,0.4566
3,4,G0100050,2016-2020,AL,NaN,NaN,Alabama,01,Barbour County,005,...,4243,859,3384,1554,436,1118,1074,709,365,0.5047
4,5,G0100070,2016-2020,AL,NaN,NaN,Alabama,01,Bibb County,007,...,4217,656,3561,1098,235,863,871,433,438,0.4500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,3218,G7201450,2016-2020,PR,NaN,NaN,Puerto Rico,72,Vega Baja Municipio,145,...,10531,2511,8020,3059,1350,1709,2644,1570,1074,0.4942
3218,3219,G7201470,2016-2020,PR,NaN,NaN,Puerto Rico,72,Vieques Municipio,147,...,1660,82,1578,525,28,497,466,219,247,0.4471
3219,3220,G7201490,2016-2020,PR,NaN,NaN,Puerto Rico,72,Villalba Municipio,149,...,4461,1160,3301,1264,656,608,853,596,257,0.5419
3220,3221,G7201510,2016-2020,PR,NaN,NaN,Puerto Rico,72,Yabucoa Municipio,151,...,6795,566,6229,2079,517,1562,1636,789,847,0.4987
3221,3222,G7201530,2016-2020,PR,NaN,NaN,Puerto Rico,72,Yauco Municipio,153,...,7213,2500,4713,2345,1102,1243,1932,1319,613,0.5080

In [ ]:
#cols = [1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39]
#f_after_dropping = df.drop(df.columns[cols],axis=1)

In [ ]:
#df_after_dropping

,1,County Code,Total,"U.S. citizen, born in the United States","U.S. citizen, born in Puerto Rico or U.S. Island Areas","U.S. citizen, born abroad of American parent(s)",U.S. citizen by naturalization,Not a U.S. citizen,Total,Income in the past 12 months below poverty level,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
0,1,County Code,Total,"U.S. citizen, born in the United States","U.S. citizen, born in Puerto Rico or U.S. Isla...","U.S. citizen, born abroad of American parent(s)",U.S. citizen by naturalization,Not a U.S. citizen,Total,Income in the past 12 months below poverty level,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
1,2,001,55639,53503,125,708,639,664,55181,8394,...,11323,2064,9259,2741,898,1843,1962,1255,707,0.4552
2,3,003,218289,208574,635,1611,3691,3778,215170,19739,...,44915,5851,39064,14209,2921,11288,9539,4370,5169,0.4566
3,4,005,25026,24294,28,65,249,390,22070,6312,...,4243,859,3384,1554,436,1118,1074,709,365,0.5047
4,5,007,22374,21907,15,98,147,207,20748,3755,...,4217,656,3561,1098,235,863,871,433,438,0.4500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,3218,145,NaN,NaN,NaN,NaN,NaN,NaN,50871,23229,...,10531,2511,8020,3059,1350,1709,2644,1570,1074,0.4942
3218,3219,147,NaN,NaN,NaN,NaN,NaN,NaN,8438,4438,...,1660,82,1578,525,28,497,466,219,247,0.4471
3219,3220,149,NaN,NaN,NaN,NaN,NaN,NaN,21757,10100,...,4461,1160,3301,1264,656,608,853,596,257,0.5419
3220,3221,151,NaN,NaN,NaN,NaN,NaN,NaN,32821,16966,...,6795,566,6229,2079,517,1562,1636,789,847,0.4987
3221,3222,153,NaN,NaN,NaN,NaN,NaN,NaN,34333,16781,...,7213,2500,4713,2345,1102,1243,1932,1319,613,0.5080

In [ ]:
#df2=df2.rename(columns=df2.iloc[0])

In [ ]:
#df_after_dropping

,1,County Code,Total,"U.S. citizen, born in the United States","U.S. citizen, born in Puerto Rico or U.S. Island Areas","U.S. citizen, born abroad of American parent(s)",U.S. citizen by naturalization,Not a U.S. citizen,Total,Income in the past 12 months below poverty level,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
0,1,County Code,Total,"U.S. citizen, born in the United States","U.S. citizen, born in Puerto Rico or U.S. Isla...","U.S. citizen, born abroad of American parent(s)",U.S. citizen by naturalization,Not a U.S. citizen,Total,Income in the past 12 months below poverty level,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
1,2,001,55639,53503,125,708,639,664,55181,8394,...,11323,2064,9259,2741,898,1843,1962,1255,707,0.4552
2,3,003,218289,208574,635,1611,3691,3778,215170,19739,...,44915,5851,39064,14209,2921,11288,9539,4370,5169,0.4566
3,4,005,25026,24294,28,65,249,390,22070,6312,...,4243,859,3384,1554,436,1118,1074,709,365,0.5047
4,5,007,22374,21907,15,98,147,207,20748,3755,...,4217,656,3561,1098,235,863,871,433,438,0.4500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,3218,145,NaN,NaN,NaN,NaN,NaN,NaN,50871,23229,...,10531,2511,8020,3059,1350,1709,2644,1570,1074,0.4942
3218,3219,147,NaN,NaN,NaN,NaN,NaN,NaN,8438,4438,...,1660,82,1578,525,28,497,466,219,247,0.4471
3219,3220,149,NaN,NaN,NaN,NaN,NaN,NaN,21757,10100,...,4461,1160,3301,1264,656,608,853,596,257,0.5419
3220,3221,151,NaN,NaN,NaN,NaN,NaN,NaN,32821,16966,...,6795,566,6229,2079,517,1562,1636,789,847,0.4987
3221,3222,153,NaN,NaN,NaN,NaN,NaN,NaN,34333,16781,...,7213,2500,4713,2345,1102,1243,1932,1319,613,0.5080

Combine the two estimates for different variables from 2020 into one dataframe

In [ ]:
#county_merge = pd.concat([df_after_dropping, df2], axis=1)

In [ ]:
df

,1,GIS Join Match Code,Data File Year,State Postal Abbreviation,Region Code,Division Code,State Name,State Code,County Name,County Code,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
0,1,GIS Join Match Code,Data File Year,State Postal Abbreviation,Region Code,Division Code,State Name,State Code,County Name,County Code,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
1,2,G0100010,2016-2020,AL,NaN,NaN,Alabama,01,Autauga County,001,...,11323,2064,9259,2741,898,1843,1962,1255,707,0.4552
2,3,G0100030,2016-2020,AL,NaN,NaN,Alabama,01,Baldwin County,003,...,44915,5851,39064,14209,2921,11288,9539,4370,5169,0.4566
3,4,G0100050,2016-2020,AL,NaN,NaN,Alabama,01,Barbour County,005,...,4243,859,3384,1554,436,1118,1074,709,365,0.5047
4,5,G0100070,2016-2020,AL,NaN,NaN,Alabama,01,Bibb County,007,...,4217,656,3561,1098,235,863,871,433,438,0.4500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,3218,G7201450,2016-2020,PR,NaN,NaN,Puerto Rico,72,Vega Baja Municipio,145,...,10531,2511,8020,3059,1350,1709,2644,1570,1074,0.4942
3218,3219,G7201470,2016-2020,PR,NaN,NaN,Puerto Rico,72,Vieques Municipio,147,...,1660,82,1578,525,28,497,466,219,247,0.4471
3219,3220,G7201490,2016-2020,PR,NaN,NaN,Puerto Rico,72,Villalba Municipio,149,...,4461,1160,3301,1264,656,608,853,596,257,0.5419
3220,3221,G7201510,2016-2020,PR,NaN,NaN,Puerto Rico,72,Yabucoa Municipio,151,...,6795,566,6229,2079,517,1562,1636,789,847,0.4987
3221,3222,G7201530,2016-2020,PR,NaN,NaN,Puerto Rico,72,Yauco Municipio,153,...,7213,2500,4713,2345,1102,1243,1932,1319,613,0.5080

Create a dataframe wit only counties in virginia

In [ ]:
VA = df[df["State Name"] == 'Virginia']

In [ ]:
VA

,1,GIS Join Match Code,Data File Year,State Postal Abbreviation,Region Code,Division Code,State Name,State Code,County Name,County Code,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
2822,2823,G5100010,2016-2020,VA,NaN,NaN,Virginia,51,Accomack County,001,...,6474,823,5651,2376,426,1950,1683,920,763,0.4562
2823,2824,G5100030,2016-2020,VA,NaN,NaN,Virginia,51,Albemarle County,003,...,20763,1248,19515,6183,723,5460,4898,2124,2774,0.4719
2824,2825,G5100050,2016-2020,VA,NaN,NaN,Virginia,51,Alleghany County,005,...,3052,523,2529,1071,288,783,836,442,394,0.4537
2825,2826,G5100070,2016-2020,VA,NaN,NaN,Virginia,51,Amelia County,007,...,2667,379,2288,746,114,632,570,265,305,0.4320
2826,2827,G5100090,2016-2020,VA,NaN,NaN,Virginia,51,Amherst County,009,...,6596,771,5825,2009,472,1537,1636,695,941,0.4239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2950,2951,G5108000,2016-2020,VA,NaN,NaN,Virginia,51,Suffolk city,800,...,18942,2312,16630,4244,955,3289,3067,1668,1399,0.4463
2951,2952,G5108100,2016-2020,VA,NaN,NaN,Virginia,51,Virginia Beach city,810,...,87806,9132,78674,20742,3589,17153,15235,7644,7591,0.4296
2952,2953,G5108200,2016-2020,VA,NaN,NaN,Virginia,51,Waynesboro city,820,...,4263,907,3356,1097,267,830,1203,522,681,0.4817
2953,2954,G5108300,2016-2020,VA,NaN,NaN,Virginia,51,Williamsburg city,830,...,1854,180,1674,676,81,595,590,253,337,0.5440
2954,2955,G5108400,2016-2020,VA,NaN,NaN,Virginia,51,Winchester city,840,...,5062,966,4096,1501,282,1219,1064,621,443,0.4384

In [ ]:
list(VA.columns.values)

[1,
 'GIS Join Match Code',
 'Data File Year',
 'State Postal Abbreviation',
 'Region Code',
 'Division Code',
 'State Name',
 'State Code',
 'County Name',
 'County Code',
 'County Subdivision Code',
 'Place Code',
 'Census Tract Code',
 'Consolidated City Code',
 'American Indian Area/Alaska Native Area/Hawaiian Home Land Code',
 'American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only) Code',
 'American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land Code',
 'American Indian Trust Land/ Hawaiian Home Land Indicator',
 'Tribal Subdivision/Remainder Code',
 'Alaska Native Regional Corporation Code',
 'Metropolitan Statistical Area/Micropolitan Statistical Area Code',
 'Combined Statistical Area Code',
 'Metropolitan Division Code',
 'New England City and Town Area Code',
 'Combined New England City and Town Area Code',
 'New England City and Town Area Division Code',
 'Urban Area Code',
 'Congressional District (2019-2021, 116th Congress) Code',
 'State Legislative District (Upper Chamber) Code',
 'State Legislative District (Lower Chamber) Code',
 '5-Digit ZIP Code Tabulation Area Code',
 'Subminor Civil Division Code',
 'School District (Elementary)/Remainder Code',
 'School District (Secondary)/Remainder Code',
 'School District (Unified)/Remainder Code',
 'Principal City Indicator',
 'Public Use Microdata Area Code',
 'Census Geographic Identifier',
 'Area Name',
 'Tribal Census Tract Code',
 'Total',
 'U.S. citizen, born in the United States',
 'U.S. citizen, born in Puerto Rico or U.S. Island Areas',
 'U.S. citizen, born abroad of American parent(s)',
 'U.S. citizen by naturalization',
 'Not a U.S. citizen',
 'Total',
 'Income in the past 12 months below poverty level',
 'Income in the past 12 months below poverty level: Male',
 'Income in the past 12 months below poverty level: Male: Under 5 years',
 'Income in the past 12 months below poverty level: Male: 5 years',
 'Income in the past 12 months below poverty level: Male: 6 to 11 years',
 'Income in the past 12 months below poverty level: Male: 12 to 14 years',
 'Income in the past 12 months below poverty level: Male: 15 years',
 'Income in the past 12 months below poverty level: Male: 16 and 17 years',
 'Income in the past 12 months below poverty level: Male: 18 to 24 years',
 'Income in the past 12 months below poverty level: Male: 25 to 34 years',
 'Income in the past 12 months below poverty level: Male: 35 to 44 years',
 'Income in the past 12 months below poverty level: Male: 45 to 54 years',
 'Income in the past 12 months below poverty level: Male: 55 to 64 years',
 'Income in the past 12 months below poverty level: Male: 65 to 74 years',
 'Income in the past 12 months below poverty level: Male: 75 years and over',
 'Income in the past 12 months below poverty level: Female',
 'Income in the past 12 months below poverty level: Female: Under 5 years',
 'Income in the past 12 months below poverty level: Female: 5 years',
 'Income in the past 12 months below poverty level: Female: 6 to 11 years',
 'Income in the past 12 months below poverty level: Female: 12 to 14 years',
 'Income in the past 12 months below poverty level: Female: 15 years',
 'Income in the past 12 months below poverty level: Female: 16 and 17 years',
 'Income in the past 12 months below poverty level: Female: 18 to 24 years',
 'Income in the past 12 months below poverty level: Female: 25 to 34 years',
 'Income in the past 12 months below poverty level: Female: 35 to 44 years',
 'Income in the past 12 months below poverty level: Female: 45 to 54 years',
 'Income in the past 12 months below poverty level: Female: 55 to 64 years',
 'Income in the past 12 months below poverty level: Female: 65 to 74 years',
 'Income in the past 12 months below poverty level: Female: 75 years and over',
 'Income in the past 12 months at or above poverty level',
 'Income in the past 12 months at or above poverty level: Male',
 'Income in the past 12 months at or above poverty level: Male: Under 5 years',
 'Income in the past 12 months at or above poverty level: Male: 5 years',
 'Income in the past 12 months at or above poverty level: Male: 6 to 11 years',
 'Income in the past 12 months at or above poverty level: Male: 12 to 14 years',
 'Income in the past 12 months at or above poverty level: Male: 15 years',
 'Income in the past 12 months at or above poverty level: Male: 16 and 17 years',
 'Income in the past 12 months at or above poverty level: Male: 18 to 24 years',
 'Income in the past 12 months at or above poverty level: Male: 25 to 34 years',
 'Income in the past 12 months at or above poverty level: Male: 35 to 44 years',
 'Income in the past 12 months at or above poverty level: Male: 45 to 54 years',
 'Income in the past 12 months at or above poverty level: Male: 55 to 64 years',
 'Income in the past 12 months at or above poverty level: Male: 65 to 74 years',
 'Income in the past 12 months at or above poverty level: Male: 75 years and over',
 'Income in the past 12 months at or above poverty level: Female',
 'Income in the past 12 months at or above poverty level: Female: Under 5 years',
 'Income in the past 12 months at or above poverty level: Female: 5 years',
 'Income in the past 12 months at or above poverty level: Female: 6 to 11 years',
 'Income in the past 12 months at or above poverty level: Female: 12 to 14 years',
 'Income in the past 12 months at or above poverty level: Female: 15 years',
 'Income in the past 12 months at or above poverty level: Female: 16 and 17 years',
 'Income in the past 12 months at or above poverty level: Female: 18 to 24 years',
 'Income in the past 12 months at or above poverty level: Female: 25 to 34 years',
 'Income in the past 12 months at or above poverty level: Female: 35 to 44 years',
 'Income in the past 12 months at or above poverty level: Female: 45 to 54 years',
 'Income in the past 12 months at or above poverty level: Female: 55 to 64 years',
 'Income in the past 12 months at or above poverty level: Female: 65 to 74 years',
 'Income in the past 12 months at or above poverty level: Female: 75 years and over',
 'Total',
 'Income in the past 12 months below poverty level',
 'Income in the past 12 months below poverty level: Under 6 years',
 'Income in the past 12 months below poverty level: 6 to 11 years',
 'Income in the past 12 months below poverty level: 12 to 17 years',
 'Income in the past 12 months below poverty level: 18 to 59 years',
 'Income in the past 12 months below poverty level: 60 to 74 years',
 'Income in the past 12 months below poverty level: 75 to 84 years',
 'Income in the past 12 months below poverty level: 85 years and over',
 'Income in the past 12 months at or above poverty level',
 'Income in the past 12 months at or above poverty level: Under 6 years',
 'Income in the past 12 months at or above poverty level: 6 to 11 years',
 'Income in the past 12 months at or above poverty level: 12 to 17 years',
 'Income in the past 12 months at or above poverty level: 18 to 59 years',
 'Income in the past 12 months at or above poverty level: 60 to 74 years',
 'Income in the past 12 months at or above poverty level: 75 to 84 years',
 'Income in the past 12 months at or above poverty level: 85 years and over',
 'Total',
 'Male',
 'Male: Under 5 years',
 'Male: Under 5 years: With a disability',
 'Male: Under 5 years: No disability',
 'Male: 5 to 17 years',
 'Male: 5 to 17 years: With a disability',
 'Male: 5 to 17 years: No disability',
 'Male: 18 to 34 years',
 'Male: 18 to 34 years: With a disability',
 'Male: 18 to 34 years: No disability',
 'Male: 35 to 64 years',
 'Male: 35 to 64 years: With a disability',
 'Male: 35 to 64 years: No disability',
 'Male: 65 to 74 years',
 'Male: 65 to 74 years: With a disability',
 'Male: 65 to 74 years: No disability',
 'Male: 75 years and over',
 'Male: 75 years and over: With a disability',
 'Male: 75 years and over: No disability',
 'Female',
 'Female: Under 5 years',
 'Female: Under 5 years: With a disability',
 'Female: Under 5 years: No disability',
 'Female: 5 to 17 years',
 'Female: 5 to 17 years: With a disability',
 'Female: 5 to 17 years: No disability',
 'Female: 18 to 34 years',
 'Female: 18 to 34 years: With a disability',
 'Female: 18 to 34 years: No disability',
 'Female: 35 to 64 years',
 'Female: 35 to 64 years: With a disability',
 'Female: 35 to 64 years: No disability',
 'Female: 65 to 74 years',
 'Female: 65 to 74 years: With a disability',
 'Female: 65 to 74 years: No disability',
 'Female: 75 years and over',
 'Female: 75 years and over: With a disability',
 'Female: 75 years and over: No disability',
 'Gini Index']

In [ ]:
votes = df4

In [ ]:
votes

,Unnamed: 0,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,11161,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,AL GORE,DEMOCRAT,5092,11925,20220315,TOTAL
1,11162,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,6352,11925,20220315,TOTAL
2,11163,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,RALPH NADER,GREEN,220,11925,20220315,TOTAL
3,11164,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,OTHER,OTHER,261,11925,20220315,TOTAL
4,11165,2000,VIRGINIA,VA,ALBEMARLE,51003,US PRESIDENT,AL GORE,DEMOCRAT,16255,36846,20220315,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3731,71966,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,OTHER,OTHER,24,12113,20220315,ELECTION DAY
3732,71967,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,OTHER,OTHER,0,12113,20220315,PROVISIONAL
3733,71968,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,2825,12113,20220315,ABSENTEE
3734,71969,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,2370,12113,20220315,ELECTION DAY
3735,71970,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,26,12113,20220315,PROVISIONAL

In [ ]:
# county_winners = votes.sort_values("candidatevotes").groupby("county_name", as_index=False).first()

In [ ]:
votes = votes.sort_values('candidatevotes', ascending=False).drop_duplicates(['county_name']).sort_values('county_name')
votes.reset_index(drop=True, inplace=True)

In [ ]:
votes

,Unnamed: 0,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,48892,2016,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,DONALD TRUMP,REPUBLICAN,8583,15818,20220315,TOTAL
1,70391,2020,VIRGINIA,VA,ALBEMARLE,51003,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,33416,64657,20220315,ABSENTEE
2,49176,2016,VIRGINIA,VA,ALEXANDRIA,51510,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,57242,75770,20220315,TOTAL
3,71519,2020,VIRGINIA,VA,ALEXANDRIA CITY,51510,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,55940,82521,20220315,ABSENTEE
4,48898,2016,VIRGINIA,VA,ALLEGHANY,51005,US PRESIDENT,DONALD TRUMP,REPUBLICAN,4874,7325,20220315,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,21238,2004,VIRGINIA,VA,WINCHESTER,51840,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,5283,9343,20220315,TOTAL
163,71959,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,5093,12113,20220315,ABSENTEE
164,49168,2016,VIRGINIA,VA,WISE,51195,US PRESIDENT,DONALD TRUMP,REPUBLICAN,12086,15163,20220315,TOTAL
165,49171,2016,VIRGINIA,VA,WYTHE,51197,US PRESIDENT,DONALD TRUMP,REPUBLICAN,10046,13343,20220315,TOTAL
166,39823,2012,VIRGINIA,VA,YORK,51199,US PRESIDENT,MITT ROMNEY,REPUBLICAN,20204,33953,20220315,TOTAL

In [ ]:
votes.rename(columns={"county_name": "County Name"})

,Unnamed: 0,year,state,state_po,County Name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,48892,2016,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,DONALD TRUMP,REPUBLICAN,8583,15818,20220315,TOTAL
1,70391,2020,VIRGINIA,VA,ALBEMARLE,51003,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,33416,64657,20220315,ABSENTEE
2,49176,2016,VIRGINIA,VA,ALEXANDRIA,51510,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,57242,75770,20220315,TOTAL
3,71519,2020,VIRGINIA,VA,ALEXANDRIA CITY,51510,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,55940,82521,20220315,ABSENTEE
4,48898,2016,VIRGINIA,VA,ALLEGHANY,51005,US PRESIDENT,DONALD TRUMP,REPUBLICAN,4874,7325,20220315,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,21238,2004,VIRGINIA,VA,WINCHESTER,51840,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,5283,9343,20220315,TOTAL
163,71959,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,5093,12113,20220315,ABSENTEE
164,49168,2016,VIRGINIA,VA,WISE,51195,US PRESIDENT,DONALD TRUMP,REPUBLICAN,12086,15163,20220315,TOTAL
165,49171,2016,VIRGINIA,VA,WYTHE,51197,US PRESIDENT,DONALD TRUMP,REPUBLICAN,10046,13343,20220315,TOTAL
166,39823,2012,VIRGINIA,VA,YORK,51199,US PRESIDENT,MITT ROMNEY,REPUBLICAN,20204,33953,20220315,TOTAL

In [ ]:
virginia_county = virginia_county.drop_duplicates()

In [ ]:
virginia_county

,1,County Code,Total,"U.S. citizen, born in the United States","U.S. citizen, born in Puerto Rico or U.S. Island Areas","U.S. citizen, born abroad of American parent(s)",U.S. citizen by naturalization,Not a U.S. citizen,Total,Income in the past 12 months below poverty level,...,With an Internet subscription: Broadband of any type,With an Internet subscription: Cellular data plan,With an Internet subscription: Cellular data plan: Cellular data plan with no other type of Internet subscription,"With an Internet subscription: Broadband such as cable, fiber optic or DSL","With an Internet subscription: Broadband such as cable, fiber optic or DSL: Broadband such as cable, fiber optic or DSL with no other type of Internet subscription",With an Internet subscription: Satellite Internet service,With an Internet subscription: Satellite Internet service: Satellite Internet service with no other type of Internet subscription,With an Internet subscription: Other service with no other type of Internet subscription,Internet access without a subscription,No Internet access
2822,2823,001,32560,29524,119,192,782,1943,32227,6373,...,9929,8310,2429,6248,1300,1444,102,10,414,3225
2823,2824,003,108819,95653,469,1470,5183,6044,101147,7753,...,37296,33759,8754,26716,2896,2301,297,86,956,3970
2824,2825,005,15030,14733,0,111,91,95,14744,2315,...,4682,3547,387,4145,1003,334,37,0,181,1619
2825,2826,007,12970,12694,0,97,73,106,12873,1382,...,3863,3171,648,2401,527,1048,123,12,63,1095
2826,2827,009,31782,30977,71,151,361,222,31002,3393,...,9139,7786,2374,5479,945,1281,262,26,282,2639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2950,2951,800,91383,86063,436,1373,1970,1541,90809,8330,...,29108,26750,4343,23420,2063,2751,170,8,880,4524
2951,2952,810,450882,394661,4085,8526,27552,16058,440653,31717,...,158092,145142,13852,141173,12107,5893,236,64,2651,11564
2952,2953,820,22300,20936,33,299,325,707,22039,3273,...,7313,6180,1251,5741,950,277,111,35,243,1599
2953,2954,830,15034,13494,30,269,434,807,10530,1604,...,3733,3386,440,3244,294,202,17,0,239,492
2954,2955,840,27912,23264,271,533,1432,2412,26876,4100,...,8464,7150,1061,7067,1158,445,77,0,411,1786

In [ ]:
#vote_county_merge = (pd.merge(virginia_county, county_winners, on='County Name'))
pd.merge(virginia_county, votes, on='County Name')

KeyError: 'County Name'

In [ ]:
print(rslt_df.columns.tolist())

In [ ]:
votes.to_csv('votes.csv')

In [ ]:
county_vote = pd.read_csv('county_vote.csv',low_memory=False)

In [ ]:
county_vote

    Party          County Name
0       R      Accomack County
1       D     Albemarle County
2       R     Alleghany County
3       R        Amelia County
4       R       Amherst County
..    ...                  ...
128     D         Suffolk city
129     D  Virginia Beach city
130     D      Waynesboro city
131     D    Williamsburg city
132     D      Winchester city

[133 rows x 2 columns]

In [ ]:
VA

,1,GIS Join Match Code,Data File Year,State Postal Abbreviation,Region Code,Division Code,State Name,State Code,County Name,County Code,...,Female: 35 to 64 years,Female: 35 to 64 years: With a disability,Female: 35 to 64 years: No disability,Female: 65 to 74 years,Female: 65 to 74 years: With a disability,Female: 65 to 74 years: No disability,Female: 75 years and over,Female: 75 years and over: With a disability,Female: 75 years and over: No disability,Gini Index
2822,2823,G5100010,2016-2020,VA,NaN,NaN,Virginia,51,Accomack County,001,...,6474,823,5651,2376,426,1950,1683,920,763,0.4562
2823,2824,G5100030,2016-2020,VA,NaN,NaN,Virginia,51,Albemarle County,003,...,20763,1248,19515,6183,723,5460,4898,2124,2774,0.4719
2824,2825,G5100050,2016-2020,VA,NaN,NaN,Virginia,51,Alleghany County,005,...,3052,523,2529,1071,288,783,836,442,394,0.4537
2825,2826,G5100070,2016-2020,VA,NaN,NaN,Virginia,51,Amelia County,007,...,2667,379,2288,746,114,632,570,265,305,0.4320
2826,2827,G5100090,2016-2020,VA,NaN,NaN,Virginia,51,Amherst County,009,...,6596,771,5825,2009,472,1537,1636,695,941,0.4239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2950,2951,G5108000,2016-2020,VA,NaN,NaN,Virginia,51,Suffolk city,800,...,18942,2312,16630,4244,955,3289,3067,1668,1399,0.4463
2951,2952,G5108100,2016-2020,VA,NaN,NaN,Virginia,51,Virginia Beach city,810,...,87806,9132,78674,20742,3589,17153,15235,7644,7591,0.4296
2952,2953,G5108200,2016-2020,VA,NaN,NaN,Virginia,51,Waynesboro city,820,...,4263,907,3356,1097,267,830,1203,522,681,0.4817
2953,2954,G5108300,2016-2020,VA,NaN,NaN,Virginia,51,Williamsburg city,830,...,1854,180,1674,676,81,595,590,253,337,0.5440
2954,2955,G5108400,2016-2020,VA,NaN,NaN,Virginia,51,Winchester city,840,...,5062,966,4096,1501,282,1219,1064,621,443,0.4384

In [ ]:
final = pd.merge(county_vote, VA, on='County Name')

In [ ]:

final.to_csv('final.csv')